import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const ClashDisplayNormal = localFont({
  src: [
    {
      path: "../../fonts/ClashDisplay-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../fonts/ClashDisplay-Semibold.ttf",
      weight: "600",
    },
    {
      path: "../../fonts/ClashDisplay-Bold.ttf",
      weight: "800",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={ClashDisplayNormal.style}>{children}</body>
    </html>
  );
}
