import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const myFont = localFont({ src: "../../fonts/ClashDisplay-Regular.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=clash-display@200,500,600,700,1&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body style={myFont.style}>{children}</body>
    </html>
  );
}
